apiVersion: v1
kind: Service
metadata:
  name: spring-test-graphql-service
spec:
  selector:
    app: spring-test-graphql-app
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-test-graphql-app
spec:
  selector:
    matchLabels:
      app: spring-test-graphql-app
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-test-graphql-app
    spec:
      containers:
        - name: spring-test-graphql-app
          image: spring-boot-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000