version: '3.5'

services:
  server:
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DB_NAME=blog
      - DB_PORT=3306
      - DB_HOST=mygraphqlblog_db
      - DB_USER=sa
      - DB_PASSWORD=pass
    depends_on:
      - db
    build: .

  db:
    container_name: mygraphqlblog_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
